#!/usr/bin/env python3
"""Resize the root boot.jpeg to the Core2 panel (320x240) and embed it as a
baseline-JPEG byte array in src/display/EmbeddedBootImage.h.

M5GFX's drawJpg() decodes baseline JPEG from PROGMEM at boot; a ~320x240 image
is a small (~20-40KB) blob, far cheaper than a raw RGB565 framebuffer.
"""
from __future__ import annotations

import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "boot.jpeg"
OUT = ROOT / "src" / "display" / "EmbeddedBootImage.h"
WIDTH, HEIGHT = 320, 240
QUALITY = 88


def main() -> int:
    img = Image.open(SRC).convert("RGB").resize((WIDTH, HEIGHT), Image.LANCZOS)
    buf = io.BytesIO()
    # baseline (non-progressive) is what the on-device TJpgDec decoder expects
    img.save(buf, format="JPEG", quality=QUALITY, optimize=True, progressive=False)
    data = buf.getvalue()

    lines = ["  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    body = ",\n".join(lines)
    OUT.write_text(
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        f"// Generated by tools/generate_boot_image.py from boot.jpeg ({WIDTH}x{HEIGHT}, q{QUALITY}).\n"
        "// AxeForging boot splash, drawn via M5.Display.drawJpg() during AppState::Booting.\n\n"
        f"constexpr uint16_t kBootImageWidth = {WIDTH};\n"
        f"constexpr uint16_t kBootImageHeight = {HEIGHT};\n"
        f"constexpr size_t kBootImageJpegLen = {len(data)};\n\n"
        "static const uint8_t kBootImageJpeg[] PROGMEM = {\n"
        f"{body}\n"
        "};\n"
    )
    print(f"Wrote {OUT} ({len(data)} bytes JPEG)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
